### ISSUE TITLE
Inappropriate authentication

### ISSUE THREAD

**Issue by gibazza** [GreyCorbel/SIDCloner#2]
Currently migrating SIDs for ~8000 users and each user takes about 40 to process with copy-sid function then after running the script for nearly 9 hours every user processed produces the following error:

ErrorDetail     : System.ComponentModel.Win32Exception (0x80004005): Inappropriate authentication
                     at GreyCorbel.SidCloner.CloneSid(String sourceIdentity, String targetIdentity)
                     at GreyCorbel.SidCloner.ProcessRecord()
Result          : Error
TargetPrincipal : targetUser
SourcePrincipal : sourceUser

Stopping and starting the script again straight away does not stop the error. Leave the script stopped for 30 mins start again and users start to process without error.

This is being used with MIM 2016 and Granfeldt PowerShell Management Agent with copy-sid being called in the Export.ps1.

Any idea why this would be occuring?

**Comment by jformacek** [comment]
Hello,
I would say it' environment-related. No idea about root cause. Will be glad to know if you find it.
Thanks

**Comment by jformacek** [comment]
So I faced the 'Inappropriate authentication' as well and found the reason: it was caused by credentials entered as netBIOSDomainName\samAccountName. When entered as userPrincipalName, everything went fine.
Updated readme accordingly.
